#  Set the Air conditioner mode when selected
- id: setmyairmodeselector
  alias: Set MyAir Mode Selector
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.myair_mode
  action:
    service: input_select.select_option
    entity_id: input_select.myair_modeselect
    data_template:
      option: '{{ states.sensor.myair_mode.state }}'

- id: setmyairacmode
  alias: Set MyAir AC mode
  initial_state: True
  trigger:
    entity_id: input_select.myair_modeselect
    platform: state
  action:
    - service: shell_command.myair_setcmd
      data_template:
        json: '%7B%22ac1%22:%7B%22info%22:%7B%22mode%22:%22{{ states.input_select.myair_modeselect.state }}%22%7D%7D%7D'

#  Set the Air conditioner fan selection when selected
- id: setmyairfanselector
  alias: Set MyAir Fan Selector
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.myair_fanspeed
  action:
    service: input_select.select_option
    entity_id: input_select.myair_fanselect
    data_template:
      option: '{{ states.sensor.myair_fanspeed.state }}'
- id: setmyairacfan
  alias: Set MyAir AC fan
  initial_state: True
  trigger:
    entity_id: input_select.myair_fanselect
    platform: state
  action:
    - service: shell_command.myair_setcmd
      data_template:
        json: '%7B%22ac1%22:%7B%22info%22:%7B%22fan%22:%22{{ states.input_select.myair_fanselect.state }}%22%7D%7D%7D'

#  Set the Air conditioner temperature when selected
- id: setmyairtempselector
  alias: Set MyAir Temp Selector
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.myair_settemp
  action:
    service: input_number.set_value
    entity_id: input_number.myair_inputsettemp
    data_template:
      value: '{{ states.sensor.myair_settemp.state }}'
- id: setmyairacTemp
  alias: Set MyAir AC Temp
  initial_state: True
  trigger:
    entity_id: input_number.myair_inputsettemp
    platform: state
  action:
    - service: shell_command.myair_setcmd
      data_template:
        json: '%7B%22ac1%22:%7B%22info%22:%7B%22setTemp%22:%22{{ states.input_number.myair_inputsettemp.state }}%22%7D%7D%7D'

#  Set the Air conditioner air flow when selected
- id: setmyairzoneairflow
  alias: Set MyAir Zone Airflow
  trigger:
    entity_id: input_number.myair_zone1,input_number.myair_zone2,input_number.myair_zone3,input_number.myair_zone4,input_number.myair_zone5,input_number.myair_zone6
    platform: state
  action:
    - service: shell_command.myair_setcmd
      data_template:
        json: '%7B%22ac1%22:%7B%22zones%22:%7B%22{{ trigger.entity_id|replace("input_number.myair_zone","z0") }}%22:%7B%22value%22:%22{{ trigger.to_state.state | int }}%22%7D%7D%7D%7D'
- id: setmyairzoneflowselector
  alias: Set MyAir Zone Airflow Selector
  trigger:
    - platform: state
      entity_id: sensor.myair_zone1_cover,sensor.myair_zone2_cover,sensor.myair_zone3_cover,sensor.myair_zone4_cover,sensor.myair_zone5_cover,sensor.myair_zone6_cover
  action:
    service: input_number.set_value
    data_template:
      entity_id: '{{ trigger.entity_id | replace("sensor.","input_number.") | replace("_cover","") }}'
      value: >
        {% if trigger.entity_id == "sensor.myair_zone1_cover" %}
          {{ states.sensor.myair_zone1_cover.state|float }}
        {% elif trigger.entity_id == "sensor.myair_zone2_cover" %}
          {{ states.sensor.myair_zone2_cover.state|float }}
        {% elif trigger.entity_id == "sensor.myair_zone3_cover" %}
          {{ states.sensor.myair_zone3_cover.state|float }}
        {% elif trigger.entity_id == "sensor.myair_zone4_cover" %}
          {{ states.sensor.myair_zone4_cover.state|float }}
        {% elif trigger.entity_id == "sensor.myair_zone5_cover" %}
          {{ states.sensor.myair_zone5_cover.state|float }}
        {% elif trigger.entity_id == "sensor.myair_zone6_cover" %}
          {{ states.sensor.myair_zone6_cover.state|float }}
        {% elif trigger.entity_id == "sensor.myair_zone7_cover" %}
          {{ states.sensor.myair_zone7_cover.state|float }}
        {% elif trigger.entity_id == "sensor.myair_zone8_cover" %}
          {{ states.sensor.myair_zone8_cover.state|float }}
        {% elif trigger.entity_id == "sensor.myair_zone9_cover" %}
          {{ states.sensor.myair_zone9_cover.state|float }}
        {% endif %}

#  Set the Air conditioner start timer  when selected
- id: setmyairstarttimer
  alias: Set MyAir Start Timer
  initial_state: True
  trigger:
    entity_id: input_number.myair_starttimer
    platform: state
  action:
    - service: shell_command.myair_setcmd
      data_template:
        json: '%7B%22ac1%22:%7B%22info%22:%7B%22countDownToOn%22:%22{{ states.input_number.myair_starttimer.state }}%22%7D%7D%7D'

#  Set the Air conditioner end timer when selected        
- id: setmyairstoptimer
  alias: Set MyAir Stop Timer
  initial_state: True
  trigger:
    entity_id: input_number.myair_stoptimer
    platform: state
  action:
    - service: shell_command.myair_setcmd
      data_template:
        json: '%7B%22ac1%22:%7B%22info%22:%7B%22countDownToOff%22:%22{{ states.input_number.myair_stoptimer.state }}%22%7D%7D%7D'

#Set the Air conditioner time when selected  
- id: setmyairzonetimeselector
  alias: Set MyAir Zone Timer Selector
  trigger:
    - platform: state
      entity_id: sensor.myair_start_timer,sensor.myair_stop_timer
  action:
    service: input_number.set_value
    data_template:
      entity_id: '{{ trigger.entity_id | replace("sensor.","input_number.") | replace("_timer","timer") }}'
      value: >
        {% if trigger.entity_id == "sensor.myair_start_timer" %}
          {{ states.sensor.myair_start_timer.state|float }}
        {% elif trigger.entity_id == "sensor.myair_stop_timer" %}
          {{ states.sensor.myair_stop_timer.state|float }}
        {% endif %}

# Set MyAir Stop Timer to 90 when Switch is turned on
- id: setmyairstoptimerbyswitch
  alias: Set MyAir Stop Timer to 90 when Switch is turned on
  initial_state: True
  trigger:
    - platform: state
      entity_id: switch.air_conditioner
      to: 'on'
      for:
        seconds: 3
  action:
    - service: shell_command.myair_setcmd
      data_template:
        json: '%7B%22ac1%22:%7B%22info%22:%7B%22countDownToOff%22:%2290%22%7D%7D%7D'

# Reset MyAir Stop Timer to 0 when Switch is turned off    
- id: resetmyairstoptimerbyswitch
  alias: Reset MyAir Stop Timer to 0 when Switch is turned off
  initial_state: True
  trigger:
    - platform: state
      entity_id: switch.air_conditioner
      to: 'off'
  action:
    - service: shell_command.myair_setcmd
      data_template:
        json: '%7B%22ac1%22:%7B%22info%22:%7B%22countDownToOff%22:%220%22%7D%7D%7D'

# plex seven news play
- id: plexplay
  alias: plex seven news play
  initial_state: True
  trigger:
    - platform: state
      entity_id: switch.myair_zone6
      to: 'on'
  action:
    - service: media_player.play_media
      entity_id: media_player.living_room
      data:
        media_content_id: '{ \"library_name\" : \"TV Shows\", \"show_name\" : \"Seven News\", \"season_number\" : 2019, \"episode_number\" : \"04-23\", \"shuffle\": \"0\" }'
        media_content_type: EPISODE

# Send Alerts from Xiaomi when the house is Armed
- id: xiaomi_alerts
  alias: alert on xiaomi sensors when armed
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002742898
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e0ac8e
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002c716b6
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002739295
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002c716d7
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002ca3100
      to: 'on'
  condition:
    condition: state
    entity_id: switch.housealarm
    state: 'on'
  action:
    - service: notify.pushbullet
      data_template:
        title: 'Motion Detected {{now().strftime("%Y%m%d-%H%M%S")}}'
        message:  '{{ states[trigger.entity_id.split(".")[0]][ trigger.entity_id.split(".")[1]].name }}  has triggered'
    - service: notify.sendgrid
      data_template:
        title: 'Motion Detected {{now().strftime("%Y%m%d-%H%M%S")}}'
        message:  '{{ states[trigger.entity_id.split(".")[0]][ trigger.entity_id.split(".")[1]].name }}  has triggered'

# Turn on the Bath Light when there is motion
- id: bathlighton
  alias: Turn on Bath Light when there is motion
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e0ac8e
      to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_158d0001e0ac8e
    below: 30
  action:
    - service: homeassistant.turn_on
      entity_id:  light.bath_light_132

# Turn off the Bath Light when there's no Motion in shower and Bathroom
- id: bathlightoff
  alias: Turn off Bath Light when there is no more motion
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e0ac8e
      to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.motion_sensor_158d0002c6382d
    state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id:  light.bath_light_132

# Turn on the Pantry Light when the door open
- id: pantrylighton
  alias: Turn on the Pantry Light when the door Opens
  trigger: 
    - platform: state
      entity_id: binary_sensor.pantry_door_18
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id:  light.pantry_light_293

# Turn off the pantry light when the door close
- id: pantrylightoff
  alias: Turn off the Pantry Light when the door Opens
  trigger: 
    - platform: state
      entity_id: binary_sensor.pantry_door_18
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id:  light.pantry_light_293

# Turn off the Pantry Light when the door open and left for more than 2 minutes
- id: pantrylightofftimer
  alias: Turn off the Pantry Light when the door Opens for more than 2 mins
  trigger: 
    - platform: state
      entity_id: binary_sensor.pantry_door_18
      to: 'on'
      for:
        minutes: 2
  action:
    - service: homeassistant.turn_off
      entity_id:  light.pantry_light_293

# Turn on the garage light then there is motion
- id: garagelighton
  alias: Turn on Garage Light when there is motion
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002c716d7
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_sensor_m_46
      to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.garage_sensor_l_48
    below: 30
  action:
    - service: homeassistant.turn_on
      entity_id:  light.garage_light_295

# Turn off the garage light then there is no motion
- id: garagelightoff
  alias: Turn off Garage Light when there is no motion
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002c716d7
      to: 'off'
    - platform: state
      entity_id: binary_sensor.garage_sensor_m_46
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id:  light.garage_light_295


# Turn on the Bath strip when there is motion
- id: bathstripon
  alias: Turn on Bath strip when there is motion
  trigger: 
    - platform: state
      entity_id: binary_sensor.m_bed_room_m_33
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id:  light.bath_stripe_294

# Turn off the Bath strip when there's no Motion
- id: bathstripoff
  alias: Turn off Bath Strip when there is no more motion
  trigger: 
    - platform: state
      entity_id: binary_sensor.m_bed_room_m_33
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id:  light.bath_stripe_294

# Alert if the Laundry door was left open for more than 10 minutes
- id: laundrydoor10mins
  trigger: 
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002ca3100
      to: 'on'
      for:
        minutes: 10
  action:
    - service: notify.pushbullet
      data_template:
        title: 'Laundry Door was left open for more than 10 minutes -  {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  'Laundry door was left open for more than 10 minutes'
    - service: notify.sendgrid
      data_template:
        title: 'Laundry Door was left open for more than 10 minutes - {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  'Laundry door was left open for more than 10 minutes'

# Alert if the Laundry door was left open for more than 60 minutes
- id: laundrydoor120mins
  trigger: 
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002ca3100
      to: 'on'
      for:
        minutes: 120
  action:
    - service: notify.pushbullet
      data_template:
        title: 'Laundry Door was left open for more than 120 minutes -  {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  'Laundry door was left open for more than 120 minutes'
    - service: notify.sendgrid
      data_template:
        title: 'Laundry Door was left open for more than 120 minutes - {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  'Laundry door was left open for more than 120 minutes'

# Alert every day at 10:00pm if any of the doors were left open. 
- id: dailydooropenalert
  trigger: 
    - platform: time
      at: '22:00:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0002739295
        state: 'on'
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0002ca3100
        state: 'on'
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0002c0e236
        state: 'on'
      - condition: state
        entity_id: binary_sensor.garage_door_32
        state: 'on'
      - condition: state
        entity_id: binary_sensor.pantry_door_18
        state: 'on' 
  action:
    - service: notify.pushbullet
      data_template:
        title: '{{ [condition.entity_id.split(".")[1]].name  }} Door was left open at 10:00pm today -  {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  '{{ [condition.entity_id.split(".")[1]].name  }} Door was left open at 10:00pm today -  {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
    - service: notify.sendgrid
      data_template:
        title: '{{ [condition.entity_id.split(".")[1]].name  }} Door was left open at 10:00pm today -  {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  '{{ [condition.entity_id.split(".")[1]].name  }} Door was left open at 10:00pm today -  {{now().strftime("%m/%d/%Y - %I:%M %p")}}'



# Alert if the Garage door was left open for more than 10 minutes
- id: garagedoor10mins
  trigger: 
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002c0e236
      to: 'on'
      for:
        minutes: 10
  action:
    - service: notify.pushbullet
      data_template:
        title: 'Garage Door was left open for more than 10 minutes -  {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  'Garage door was left open for more than 10 minutes'
    - service: notify.sendgrid
      data_template:
        title: 'Garage Door was left open for more than 10 minutes - {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  'Garage door was left open for more than 10 minutes'

# Alert if the Laundry door was left open for more than 60 minutes
- id: garagedoor120mins
  trigger: 
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002c0e236
      to: 'on'
      for:
        minutes: 120
  action:
    - service: notify.pushbullet
      data_template:
        title: 'Garage Door was left open for more than 120 minutes -  {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  'Garage door was left open for more than 120 minutes'
    - service: notify.sendgrid
      data_template:
        title: 'Garage Door was left open for more than 120 minutes - {{now().strftime("%m/%d/%Y - %I:%M %p")}}'
        message:  'Garage door was left open for more than 120 minutes'


# Turn on the Front Outdoor light then there the garage door open
- id: frontoutdoorgaragelight
  alias: Turn on Front Outdoor Light when garage door open
  trigger: 
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002c0e236
      to: 'on'
      for: 
        seconds: 2
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service : script.turn_on
      entity_id: script.garagelight