homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_value
  longitude: !secret longitude_value
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 7
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Perth
  # Customization file
  customize: !include customize.yaml

  whitelist_external_dirs:
    - /share
   #- /home/homeassistant/

  # Enable MFA
  auth_mfa_modules:
    - type: totp

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret http_password
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# enable the recorder component
recorder:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


shell_command:
  myair_setcmd: !secret myair_set_cmd
  house_alarm_on: "/usr/bin/curl -X GET 'http://10.1.1.150:3480/data_request?id=action&output_format=json&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=SetHouseMode&Mode=2'"
  house_alarm_off: "/usr/bin/curl -X GET 'http://10.1.1.150:3480/data_request?id=action&output_format=json&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=SetHouseMode&Mode=1'"

# Sensors
sensor: !include sensor.yaml

# Text to speech
tts:
  - platform: google_translate

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
camera: !include camera.yaml
input_boolean: !include input_boolean.yaml

# Vera
vera:
  vera_controller_url: !secret vera_url


#google assistant
google_assistant:
  project_id: !secret google_project_id 
  api_key: google_api_key
  exposed_domains:
    - switch
    - light
    - group
    - media_player
    - scene
    - camera

#emulated hue
emulated_hue:
  expose_by_default: false
  entities:
    light.alfresco_light_260:
      hidden: false
    light.bath_light_132:
      hidden: false
    light.bath_stripe:
      hidden: false
    light.living_mood_lights:
      hidden: false
    light.office_dimmer_120:
      hidden: false
    light.front_outdoor_lights_59:
      hidden: false
    light.kitchen_light_135:
      hidden: false
    light.living_light_129:
      hidden: false
    light.living_mood_lights:
      hidden: false
    light.master_dimmer_123:
      hidden: false
    light.garage_light:
      hidden: false
    switch.air_conditioner:
      hidden: false
    switch.bedheater_38:
      hidden: false
    switch.housealarm:
      hidden: false
    switch.living_music:
      hidden: false
    switch.alfresco_music:
      hidden: false
    switch.nightmood:
      hidden: false


# MyAir Inputs
input_select:
  myair_modeselect:
    name: Aircon Mode
    options:
     - cool
     - heat
     - vent
     - dry
    icon: mdi:air-conditioner

  myair_fanselect:
    name: Aircon Fan
    options:
     - low
     - medium
     - high
     - auto
    icon: mdi:speedometer

input_number:
  myair_inputsettemp:
    name: Aircon Temp
    min: 16
    max: 32
    unit_of_measurement: ºC
    icon: mdi:thermometer
  myair_zone1:
    name: Living Airflow
    min: 5
    max: 100
    unit_of_measurement: "%"
    step: 5
    icon: mdi:sofa
  myair_zone2:
    name: Theater Airflow
    min: 5
    max: 100
    unit_of_measurement: "%"
    step: 5
    icon: mdi:theater
  myair_zone3:
    name: Master Bed Airflow
    min: 5
    max: 100
    unit_of_measurement: "%"
    step: 5
    icon: mdi:hotel
  myair_zone4:
    name: Bed 2 Airflow
    min: 5
    max: 100
    unit_of_measurement: "%"
    step: 5
    icon: mdi:hotel
  myair_zone5:
    name: Bed 3 Airflow
    min: 5
    max: 100
    unit_of_measurement: "%"
    step: 5
    icon: mdi:hotel
  myair_zone6:
    name: Bed 4 Airflow
    min: 5
    max: 100
    unit_of_measurement: "%"
    step: 5
    icon: mdi:hotel
  myair_starttimer:
    name: Time to Start
    min: 0
    max: 200
    step: 5
    icon: mdi:clock-start
    unit_of_measurement: "mins"
  myair_stoptimer:
    name: Time to Stop 
    min: 0
    max: 200
    step: 5
    unit_of_measurement: "mins"
    icon: mdi:clock-end

# Yamaha RX-V473 and Plex
media_player:
  - platform: yamaha
    host: 10.1.1.154
  - platform: plex

# Xiaomi
xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key

# Lovelace
lovelace:
  mode: yaml


weather:
  - platform: darksky
    api_key: !secret darksky_key
    latitude: !secret darksky_lat
    longitude: !secret darksky_long
    mode: daily


# pushbullet & sendgrid
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key
  - name: sendgrid
    platform: sendgrid
    api_key: !secret sendgrid_key
    sender: !secret sendgrid_sender
    recipient: !secret sendgrid_receiver

# SONOS
sonos:
  media_player:
    hosts: 
      - 10.1.1.159
      - 10.1.1.160
      - 10.1.1.161

# Harmony Hub for IR
remote:
  - platform: harmony
    name: living
    host: 10.1.1.210

# UniFi
device_tracker:
  - platform: unifi
    host: 10.1.1.218
    username: !secret unifi_username
    password: !secret unifi_password
    interval_seconds: 10
    verify_ssl: false
    ssid_filter:
      - 'theparadise'
    new_device_defaults:
      track_new_devices: false

# Ring
ring:
  username: !secret ring_username 
  password: !secret ring_password


# Rain Machine (Sprinkler System)
rainmachine:
  controllers:
    - ip_address: 10.1.1.179
      password: !secret rainmachine_password